# These are supported funding model platforms

github: null
patreon: null # Replace with a single Patreon username
open_collective: stylus
ko_fi: null # Replace with a single Ko-fi username
tidelift: null # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: null # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: null # Replace with a single Liberapay username
issuehunt: null # Replace with a single IssueHunt username
otechie: null # Replace with a single Otechie username
custom: null # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
